#服务端口
server:
  port: 8080

#数据库配置
spring:
  datasource:
    url: jdbc:mysql://192.168.100.10:3306/lark_security?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  security:
    user:
      name: admin
      password: admin
  redis:
    host: 192.168.108.171
    port: 6379
    password: 123456
    database: 1

# mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yunjia.lark.model

# swagger2
swagger2:
  enable: true
  basePackage: com.yunjia.lark.controller
  title: lark-cloud
  description: lark-cloud
  termsOfServiceUrl: http://localhost:8001/
  version: 1.0

ACC:
  ReadmName: www.lark.com
  digest-realm: www.lark.com
  login-url: /login.html
  secret-expire: 180000
  ip-filter-expire: 300
  algorithm: MD5
  secret-max-apply: 10
  forbidden: /forbidden.html
  JWT:
    header: Authorization
    secret: $2a$10$tVwiKCrBDR68DcpaLqG4LOwGjYiG4cmB1.GhxeXvm0sdYazGDl6Xu
    expiration: 604800
    tokenHead: "Bearer "